version: '3.8'
services:
  database:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paradiseguardian
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d paradiseguardian"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./paradiseguardian-backend
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_URL=postgres://admin:admin@database:5432/paradiseguardian
      - JWT_SECRET=supersecreto
      - REFRESH_SECRET=otro_secreto_aun_mas_largo
      - PORT=5000
  
  frontend:
    build: ./paradiseguardian-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
      - HOST=0.0.0.0

volumes:
  pgdata: 